apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-java-app
spec:
  type: LoadBalancer
  selector:
    app: my-java-app
  ports:
    - port: 80
      targetPort: 8080
